## get susie output variants into a format vep can understand

eventually this will be part of pipeline

In [8]:
import pandas as pd
import numpy as np
import os

In [5]:
df = pd.read_csv("/home/klawren/oak/pcqtls/data/references/selected_tissue_ids.csv", header=0)
tissue_ids = list(df['Tissue'])

In [9]:
for tissue_id in tissue_ids:
    path = f'/home/klawren/oak/pcqtls/output/clusters_tami/{tissue_id}_clusters_all_chr.csv.txt'
    new_path = f'/home/klawren/oak/pcqtls/output/clusters_tami/{tissue_id}_clusters_all_chr.csv'
    os.rename(path, new_path)

In [ ]:
# combine cluster dfs into one with all protein coding clusters

path = 
out_path =

,N_genes,Transcripts,Genes,Perc_cor,Mean_cor,Mean_pos_cor,Mean_neg_cor,Chromosome,Tissue
0,3,"ENSG00000099937.10,ENSG00000099940.11,ENSG0000...","SERPIND1, SNAP29, PI4KA",100,-0.052,0.376,-0.266,22,Adipose_Subcutaneous
1,3,"ENSG00000240972.1,ENSG00000133433.10,ENSG00000...","DDTL, GSTT2B, MIF",100,-0.117,0.361,-0.357,22,Adipose_Subcutaneous
2,3,"ENSG00000130489.14,ENSG00000025708.13,ENSG0000...","TYMP, SCO2, ODF3B",100,0.379,0.379,NaN,22,Adipose_Subcutaneous
3,2,"ENSG00000099968.17,ENSG00000015475.18","BID, BCL2L13",100,0.246,0.246,NaN,22,Adipose_Subcutaneous
4,2,"ENSG00000183785.14,ENSG00000184979.9","TUBA8, USP18",100,0.360,0.360,NaN,22,Adipose_Subcutaneous
5,2,"ENSG00000183628.12,ENSG00000100033.16","PRODH, DGCR6",100,0.281,0.281,NaN,22,Adipose_Subcutaneous
6,2,"ENSG00000184058.12,ENSG00000215012.8","TBX1, C22orf29",100,0.243,0.243,NaN,22,Adipose_Subcutaneous
7,2,"ENSG00000099957.16,ENSG00000099960.12","P2RX6, SLC7A4",100,0.202,0.202,NaN,22,Adipose_Subcutaneous
8,2,"ENSG00000099953.9,ENSG00000099956.18","MMP11, SMARCB1",100,0.273,0.273,NaN,22,Adipose_Subcutaneous
9,2,"ENSG00000099991.17,ENSG00000099994.10","CABIN1, SUSD2",100,0.297,0.297,NaN,22,Adipose_Subcutaneous
10,2,"ENSG00000100276.9,ENSG00000100280.16","RASL10A, AP1B1",100,0.337,0.337,NaN,22,Adipose_Subcutaneous
11,2,"ENSG00000239282.7,ENSG00000099992.15","TBC1D10A, GATSL3",100,0.460,0.460,NaN,22,Adipose_Subcutaneous
12,2,"ENSG00000100234.11,ENSG00000185666.14","TIMP3, SYN3",100,0.337,0.337,NaN,22,Adipose_Subcutaneous
13,2,"ENSG00000221963.5,ENSG00000128313.2","APOL5, APOL6",100,0.303,0.303,NaN,22,Adipose_Subcutaneous
14,2,"ENSG00000128335.13,ENSG00000100342.20","APOL1, APOL2",100,0.276,0.276,NaN,22,Adipose_Subcutaneous
15,2,"ENSG00000128309.16,ENSG00000128311.13","MPST, TST",100,0.276,0.276,NaN,22,Adipose_Subcutaneous
16,2,"ENSG00000100060.17,ENSG00000100065.14","MFNG, CARD10",100,0.346,0.346,NaN,22,Adipose_Subcutaneous
17,2,"ENSG00000100139.13,ENSG00000128346.10","MICALL1, C22orf23",100,0.301,0.301,NaN,22,Adipose_Subcutaneous
18,2,"ENSG00000100151.15,ENSG00000100156.10","PICK1, SLC16A8",100,0.341,0.341,NaN,22,Adipose_Subcutaneous
19,2,"ENSG00000100221.10,ENSG00000100226.15","JOSD1, GTPBP1",100,0.291,0.291,NaN,22,Adipose_Subcutaneous
20,2,"ENSG00000244509.3,ENSG00000243811.8","APOBEC3D, APOBEC3C",100,0.392,0.392,NaN,22,Adipose_Subcutaneous
21,2,"ENSG00000100403.11,ENSG00000167074.14","ZC3H7B, TEF",100,0.212,0.212,NaN,22,Adipose_Subcutaneous
22,2,"ENSG00000100300.17,ENSG00000100304.12","TSPO, TTLL12",100,0.248,0.248,NaN,22,Adipose_Subcutaneous
23,2,"ENSG00000093000.18,ENSG00000100364.18","NUP50, KIAA0930",100,0.210,0.210,NaN,22,Adipose_Subcutaneous
24,2,"ENSG00000075240.16,ENSG00000100422.13","GRAMD4, CERK",100,0.341,0.341,NaN,22,Adipose_Subcutaneous
25,2,"ENSG00000100429.17,ENSG00000188130.13","HDAC10, MAPK12",100,0.318,0.318,NaN,22,Adipose_Subcutaneous
26,2,"ENSG00000251322.7,ENSG00000100312.10","ACR, SHANK3",100,0.242,0.242,NaN,22,Adipose_Subcutaneous

/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_1_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_2_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_3_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_4_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_5_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_6_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_7_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_8_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_9_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_10_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_11_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_12_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_13_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_14_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_15_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_16_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_17_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_18_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_19_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_20_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_21_proteincoding.csv
/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/Adipose_Subcutaneous/clusters_chr_22_proteincoding.csv

In [14]:
for tissue_id in tissue_ids:
    out_path = f'/home/klawren/oak/pcqtls/output/clusters_proteincoding_tami/{tissue_id}_clusters_all_chr.csv'
    cluster_dfs = []
    for chr_id in range(1,23):
        in_path = f'/home/klawren/oak/coexp_eqtl/tami_eqtl_proejct/output/1_correlations/{tissue_id}/clusters_chr_{chr_id}_proteincoding.csv'
        cluster_dfs.append(pd.read_csv(in_path))
    pd.concat(cluster_dfs).to_csv(out_path)

In [3]:
TISSUE='Adipose_Subcutaneous'

In [7]:
expression_df = pd.read_csv(f'/home/klawren/oak/pcqtls/data/processed/normalized_expression_tami/{TISSUE}.v8.normalized_expression.bed', sep='\t')

In [9]:
expression_df = expression_df[expression_df['#chr'] == 'chr22']

In [63]:
'/home/klawren/oak/pcqtls/output/pcqtl/Adipose_Subcutaneous/Adipose_Subcutaneous.v8.pc_1.susie.txt'susie_path = 
susie_df = pd.read_csv(susie_path, sep='\t', index_col=0)

In [34]:
cluster_df = pd.read_csv('/home/klawren/oak/pcqtls/output/clusters_tami/Adipose_Subcutaneous_clusters_all_chr.csv.txt', sep=',')
cluster_df

,Unnamed: 0,N_genes,Transcripts,Genes,Perc_cor,Mean_cor,Mean_pos_cor,Mean_neg_cor,Chromosome,Tissue
0,0,9,"ENSG00000203786.6,ENSG00000197084.5,ENSG000001...","IVL, SPRR3, SPRR2D, SPRR1B, SPRR1A, LCE1C, SPR...",72.222,0.454,0.454,NaN,1,Adipose_Subcutaneous
1,1,8,"ENSG00000143631.10,ENSG00000143520.6,ENSG00000...","FLG2, CRNN, FLG, IVL, CRCT1, LCE1C, C1orf68, KPRP",75.000,0.438,0.438,NaN,1,Adipose_Subcutaneous
2,2,7,"ENSG00000225972.1,ENSG00000225630.1,ENSG000002...","MTCO3P12, MTND2P28, MTND1P23, MTCO2P12, MTCO1P...",76.190,0.430,0.430,NaN,1,Adipose_Subcutaneous
3,3,7,"ENSG00000169474.4,ENSG00000163209.14,ENSG00000...","SPRR2G, SPRR3, SPRR2D, SPRR1B, SPRR1A, SPRR2E,...",76.190,0.496,0.496,NaN,1,Adipose_Subcutaneous
4,4,5,"ENSG00000168765.16,ENSG00000213366.12,ENSG0000...","GSTM1, GSTM5, GSTM3, GSTM4, GSTM2",100.000,0.472,0.472,NaN,1,Adipose_Subcutaneous
...,...,...,...,...,...,...,...,...,...,...
2264,65,2,"ENSG00000075240.16,ENSG00000100422.13","GRAMD4, CERK",100.000,0.341,0.341,NaN,22,Adipose_Subcutaneous
2265,66,2,"ENSG00000260708.1,ENSG00000054611.13","TBC1D22A, CTA-29F11.1",100.000,-0.261,NaN,-0.261,22,Adipose_Subcutaneous
2266,67,2,"ENSG00000213279.2,ENSG00000235111.1","RP1-29C18.9, RP1-29C18.8",100.000,0.213,0.213,NaN,22,Adipose_Subcutaneous
2267,68,2,"ENSG00000100429.17,ENSG00000188130.13","HDAC10, MAPK12",100.000,0.318,0.318,NaN,22,Adipose_Subcutaneous
2268,69,2,"ENSG00000225929.1,ENSG00000100312.10","ACR, AC000036.4",100.000,0.354,0.354,NaN,22,Adipose_Subcutaneous

In [8]:
cluster_df['Transcripts'].str.replace(',','_')

0       ENSG00000203786.6_ENSG00000197084.5_ENSG000001...
1       ENSG00000143631.10_ENSG00000143520.6_ENSG00000...
2       ENSG00000225972.1_ENSG00000225630.1_ENSG000002...
3       ENSG00000169474.4_ENSG00000163209.14_ENSG00000...
4       ENSG00000168765.16_ENSG00000213366.12_ENSG0000...
                              ...
2264                ENSG00000075240.16_ENSG00000100422.13
2265                 ENSG00000260708.1_ENSG00000054611.13
2266                  ENSG00000213279.2_ENSG00000235111.1
2267                ENSG00000100429.17_ENSG00000188130.13
2268                 ENSG00000225929.1_ENSG00000100312.10
Name: Transcripts, Length: 2269, dtype: object

In [18]:
cluster_df['Transcripts'].iloc[0]

'ENSG00000203786.6,ENSG00000197084.5,ENSG00000163207.6,ENSG00000169474.4,ENSG00000163209.14,ENSG00000169469.8,ENSG00000163216.6,ENSG00000241794.1,ENSG00000203785.8'

,Transcript_name,Gene_name,Chromosome,Start,End,Mean_position,Distance_rank
0,ENSG00000223972.5,DDX11L1,chr1,11869,14403,13136.0,1
1,ENSG00000278267.1,MIR6859-1,chr1,17369,17436,17402.5,2
2,ENSG00000227232.5,WASH7P,chr1,14410,29553,21981.5,3
3,ENSG00000243485.5,MIR1302-2HG,chr1,29571,31109,30340.0,4
4,ENSG00000237613.2,FAM138A,chr1,34554,36081,35317.5,5
...,...,...,...,...,...,...,...
56195,ENSG00000223484.7_PAR_Y,TRPC6P,chrY,57171890,57172769,57172329.5,56196
56196,ENSG00000124334.17_PAR_Y,IL9R,chrY,57184101,57197337,57190719.0,56197
56197,ENSG00000185203.12_PAR_Y,WASIR1,chrY,57201143,57203357,57202250.0,56198
56198,ENSG00000182484.15_PAR_Y,WASH6P,chrY,57207346,57212183,57209764.5,56199
56199,ENSG00000227159.8_PAR_Y,DDX11L16,chrY,57212231,57214397,57213314.0,56200

In [28]:
row=cluster_df.iloc[0]

In [33]:
cluster_gene_df = gencode_df[gencode_df['Transcript_name'].isin(row['Transcripts'].split(','))]
cluster_gene_df['Start'].min()

152759561

In [ ]:
def get_min_tss(row):
    cluster_gene_df = gencode_df[gencode_df['Transcript_name'].isin(row['Transcripts'].split(','))]
    return cluster_gene_df['Start'].min()